# Generated by Django 6.0.5 on 2026-05-17 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('images', models.JSONField(blank=True, default=list)),
                ('desc', models.TextField()),
                ('full_details', models.TextField(blank=True, null=True)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('features', models.JSONField(blank=True, default=list)),
                ('customizable', models.BooleanField(default=False)),
                ('customization_label', models.CharField(blank=True, max_length=255, null=True)),
                ('customization_placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.topic')),
            ],
        ),
    ]
